In [1]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
import numpy as np

arr = np.array([0, 2, 0, 4, 0, 6, 0, 8])
nonzero_indices = np.nonzero(arr)
print(nonzero_indices)


(array([1, 3, 5, 7]),)


### Python Dictionary Notes

https://www.datacamp.com/tutorial/python-dictionary-comprehension

In [1]:
''' 
Open a file like
1 Dog
2 Cat
and convert into dictionary
'''

def dictionary_maker(filename):
    my_dict={}
    with open(filename, 'r') as file:
        for line in file:
            line.split('\n')
            key,value=line.split()
            my_dict[key]=value
        return my_dict
filename=("message_file.txt")
dictionary_maker(filename)


{'296': 'land',
 '3': 'sun',
 '216': 'too',
 '197': 'huge',
 '237': 'dont',
 '249': 'such',
 '81': 'noun',
 '113': 'student',
 '30': 'brown',
 '111': 'complete',
 '157': 'play',
 '165': 'cook',
 '188': 'yard',
 '195': 'clock',
 '105': 'would',
 '116': 'plain',
 '293': 'excite',
 '137': 'fire',
 '178': 'wish',
 '211': 'cool',
 '87': 'child',
 '275': 'past',
 '261': 'colony',
 '186': 'oil',
 '292': 'dog',
 '125': 'back',
 '289': 'money',
 '103': 'kind',
 '19': 'open',
 '241': 'finger',
 '100': 'touch',
 '248': 'are',
 '29': 'dad',
 '236': 'am',
 '74': 'modern',
 '200': 'meant',
 '15': 'ocean',
 '229': 'pitch',
 '151': 'suit',
 '46': 'town',
 '59': 'east',
 '194': 'over',
 '108': 'group',
 '65': 'good',
 '114': 'kind',
 '170': 'down',
 '89': 'band',
 '214': 'especially',
 '164': 'organ',
 '12': 'of',
 '85': 'fire',
 '73': 'out',
 '205': 'area',
 '167': 'touch',
 '123': 'happen',
 '76': 'sat',
 '120': 'electric',
 '119': 'wrote',
 '66': 'buy',
 '8': 'lot',
 '117': 'stop',
 '133': 'corn',
 

In [3]:
#Convert a string line by line and split by space to make a dictionary

a="Hello 1\n World 2"
mydict={}
for i in a.split('\n'):
    key,value=i.split()
    mydict[key]=value
print(mydict)

{'Hello': '1', 'World': '2'}


In [12]:
a = "Hello 1\nWorld 2"

mydict = {key: value for line in a.split('\n') if line for key, value in [line.split()]}

print(mydict)


{'Hello': '1', 'World': '2'}


In [13]:
a="Hello 1\n World 2"
mydict={i[0]:i[1] for i in a.split('\n')}
print(mydict)

{'H': 'e', ' ': 'W'}


# Triangle Dictionary Question

I need a function called decode(message_file) that can read in an encoded message from a .txt file and return the decoded version as a string.

Here's an example of what the message_file .txt file will look like:

3 love

6 computers

2 dogs

4 cats

1 I

5 you

As you can see, each word is associated with a number. Imagine you ordered all those numbers from smallest to biggest and arranged them into a pyramid. Each line of the pyramid includes one more number than the line before it:

1

2 3

4 5 6

The numbers at the end of each line (1, 3 and 6) correspond to the words that are part of the message. You should ignore all the other words. So for the example input file above, the message words are:

1: I

3: love

6: computers

and your function should return the string "I love computers"

In [108]:
def decode(message_file):
	"""
	Function that takes a string for input filename and returns a string
	containing the decoded message.
	"""
	# create an empty dictionary to store the number and associated word read from file
	message_dict = {}
	
	# open file to read
	file = open(message_file)
	
	# loop over the file line by line
	for line in file:
		# remove leading and trailing whitespace from line and split the line to get the number and word in data list
		data = line.strip().split()
		# insert the number as key and word as value
		message_dict[int(data[0])] = data[1]
		
	file.close() # close the file

	# get the list of keys of the dictionary in numbers list
	numbers = list(message_dict.keys())
	numbers.sort() # sort the numbers list in ascending order
	
	# create a list of lists where the first element is a list containing first value of numbers
	pyramid = [[numbers[0]]]
	
	i = 1 # set i to 1
	current_list_length = len(pyramid[i-1]) + 1 # determine the length of next row of pyramid
	row = [] # create an empty list for row
	# loop over the numbers list
	while i < len(numbers):
		# row contains less elements than current_list_length
		if len(row) < current_list_length:
			row.append(numbers[i]) # append ith element of numbers to row
			i = i + 1 # increment i by 1
		else: # row contains current_list_length number of elements
			pyramid.append(row) # append the row to pyramid
			row = []  # set row to empty list
			current_list_length = len(pyramid[len(pyramid)-1]) + 1 # determine the length of next row of pyramid
					
	# row was not added to pyramid, append the row to pyramid
	if row != []:
		pyramid.append(row)
	
	message = "" # set message to empty string
	
	# loop over the rows of pyramid
	for i in range(len(pyramid)):
		message += message_dict[pyramid[i][-1]] + " " # append the last word of current list of pyramid to message followed by a space
		
	return message.strip() # remove leading and trailing whitespace from message

message_file = 'message_file.txt'
decoded_message = decode(message_file)
print(decoded_message)

opposite sun rain think ocean to winter wild it ready buy card possible would electric stay post paragraph produce state our compare touch possible


In [111]:
'''
Attempt at simpler verision -> works lessgo
1
2 3
4 5 6

we only end terms on each line
End terms are triangular sequence 1,3,6,10
formula for nth term in tri sequnce = n*(n+1)/2
Tth term = Seel below cell
'''
#making a dictionary of input file using k,v
import math

my_dict={}

def dictionary_maker(filename):
    my_dict={}
    with open(filename, 'r') as file:
        for line in file:
            line.split('\n')
            key,value=line.split()
            my_dict[int(key)]=value
    last_term=max(my_dict)    
    #print(last_term)
    total_terms_finder(last_term,my_dict)
    return 
    
#lets find the required terms by finding max key and findin the n terms between 1 and this max value      
def total_terms_finder(last_term,my_dict):
    T_n_term=last_term
    #now we know the max term, lets find the n terms between o and t_n_term
    #[n*(n+1)]/2=T_n_term, lets find n terms
    # n^2 + n - 2* T_n_term = 0; need to find root to find n
    root_num = -1 + (math.sqrt((1**2) - 4 * (1) * (-1)*(2*T_n_term)))
    root_deno = 2 * 1 #2a
    root = root_num//root_deno
    total_terms=root
    TriangularTermsGenerator(int(total_terms),my_dict)
    return total_terms
    
def TriangularTermsGenerator(total_terms,my_dict):
    decode_list=[]
    for i in range(1,total_terms+1):
        decode_list.append(i*(i+1)//2)
    decode_message(decode_list,my_dict)
    print(decode_list)

def decode_message(decode_list, my_dict):
    message = ""
    for key in decode_list:
        if key in my_dict:
            message += my_dict[key] + " "

    print(message.strip()) 
filename=("message_file.txt")
dictionary_maker(filename)


opposite sun rain think ocean to winter wild it ready buy card possible would electric stay post paragraph produce state our compare touch possible
[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300]


In [24]:
def TriangularSequence(nums):
    res=[]
    for i in range(1,nums+1):
        term=(i*(i+1))//2
        res.append(term)
    return res
print(Triangular(24))
# but how do we know 300 is the 24th Term ?
# x=(-b+√(b²-4ac))/(2a)
print("--------------------------")
import math
def T_term_finder(a,b,c):
    root_numerator= -1+ (math.sqrt((b**2)-4*(a)*(c)))
    root_denominator=2*a
    return root_numerator//root_denominator
    
a=1
b=1
#-4ac=4.1.-600
c=-600
print(T_term_finder(a,b,c))
'''

'''

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300]
--------------------------
24.0


'\n\n'

```
Certainly! Here's the explanation in plain text format:

To determine the term number (n) in a triangular sequence corresponding to the nth term (T_n = 300), the formula T_n = n*(n + 1)/2 is used. Given T_n = 300, the formula is rearranged:

1. 300 = n * (n + 1)//2
2. Multiply both sides by 2 to eliminate the fraction: 600 = n * (n + 1)
3. Rearrange the equation into a quadratic form: n^2 + n - 600 = 0
4. Apply the quadratic formula: x=(-b+√(b²-4ac))/(2a): n = -1 + \sqrt(1 + 4 \cdot 600}}}{2}\)
5. Calculate the expression inside the square root: \(n = \frac{{-1 + \sqrt{2401}}}{2}\)
6. Simplify: \(n = \frac{{-1 + 49}}{2} = 24\)

Therefore, the term number corresponding to T_n = 300 in the triangular sequence is n = 24.

In [22]:
# x=(-b+√(b²-4ac))/(2a)
import math
def T_term_finder(a,b,c):
    root_numerator= -1+ (math.sqrt((b**2)-4*(a)*(c)))
    root_denominator=2*a
    return root_numerator//root_denominator
    
a=1
b=1
#-4ac=4.1.-600
c=-600
print(T_term_finder(a,b,c))

24.0


In [74]:
def dictionary_maker(filename):
    my_dict={}
    with open(filename, 'r') as file:
        for line in file:
            line.split('\n')
            key,value=line.split()
            my_dict[key]=value
    #last_term=total_terms_finder(int(max(my_dict)))
        return my_dict
filename=("message_file.txt")
#dictionary_maker(filename)